// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4i2JWQdoHs7miQctz_MCMGMlyHt4qqM0',
    appId: '1:1005714709910:web:5974af2e6dcb8c0a94d1b7',
    messagingSenderId: '1005714709910',
    projectId: 'emmafirebaseprueba',
    authDomain: 'emmafirebaseprueba.firebaseapp.com',
    storageBucket: 'emmafirebaseprueba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2KTTFh44RyQMSBm_uz2ru1fJHEwAJ09s',
    appId: '1:1005714709910:android:604deb8af4636b7e94d1b7',
    messagingSenderId: '1005714709910',
    projectId: 'emmafirebaseprueba',
    storageBucket: 'emmafirebaseprueba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0fNpXiPOgeMNqWxIWnoB-OkIQ2Jyfzok',
    appId: '1:1005714709910:ios:fe6c86c291b8ad5c94d1b7',
    messagingSenderId: '1005714709910',
    projectId: 'emmafirebaseprueba',
    storageBucket: 'emmafirebaseprueba.firebasestorage.app',
    iosBundleId: 'com.example.emmaFlutterExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0fNpXiPOgeMNqWxIWnoB-OkIQ2Jyfzok',
    appId: '1:1005714709910:ios:fe6c86c291b8ad5c94d1b7',
    messagingSenderId: '1005714709910',
    projectId: 'emmafirebaseprueba',
    storageBucket: 'emmafirebaseprueba.firebasestorage.app',
    iosBundleId: 'com.example.emmaFlutterExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4i2JWQdoHs7miQctz_MCMGMlyHt4qqM0',
    appId: '1:1005714709910:web:4d2a609379c5049e94d1b7',
    messagingSenderId: '1005714709910',
    projectId: 'emmafirebaseprueba',
    authDomain: 'emmafirebaseprueba.firebaseapp.com',
    storageBucket: 'emmafirebaseprueba.firebasestorage.app',
  );
}
